logging:
  level:
     io:
        pivotal: DEBUG
spring:
  sleuth:
    sampler:
      probability: 1.0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
